#!/bin/sh

tests_dir="`pwd`/tests"
export CORGI="`pwd`/src/corgi"
find "${tests_dir}" -perm 0755 -name "test_*" | sort | while read cmd
do
  echo "------------ ${cmd} ------------"
  "${cmd}"
  if [ "$?" = 0 ]; then
    echo "${cmd}: OK"
  else
    echo "${cmd}: NG"
  fi
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
